/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wikitext_parser;

import com.lucaskjaerozhang.wikitext_parser.WikiTextLexer;
import java.util.Arrays;
import java.util.List;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.Token;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import wikitext_parser.util.TestErrorListener;

class WikiTextLexerTest {
  private List<Token> getTokensFromString(String testString) {
    WikiTextLexer lexer = new WikiTextLexer(CharStreams.fromString(testString));
    lexer.addErrorListener(new TestErrorListener());
    CommonTokenStream tokens = new CommonTokenStream(lexer);
    tokens.fill();
    return tokens.getTokens();
  }

  private List<Integer> getTokenTypes(List<Token> tokens) {
    return tokens.stream().map(Token::getType).toList();
  }

  @Test
  void headersAreRecognized() {
    List<Integer> tokenTypes = getTokenTypes(getTokensFromString("== Header =="));
    List<Integer> assertAgainst =
        Arrays.asList(
            WikiTextLexer.T__1, WikiTextLexer.TEXT, WikiTextLexer.T__1, WikiTextLexer.EOF);

    Assertions.assertIterableEquals(tokenTypes, assertAgainst);
  }
}
