coverage:
  status:
    project:
      default:
        # basic
        target: 90
        threshold: 1%
        flags:
          - unittest
        paths:
          - "lib/src/main/java"
          - "lib/src/test/java"
    patch:
      default:
        target: 75