/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wikitext_parser;

import com.lucaskjaerozhang.wikitext_parser.WikiTextBaseListener;

public class Library extends WikiTextBaseListener {
    public boolean someLibraryMethod() {
        return true;
    }
}
