name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: '2'

      - name: Set up JDK 18
        uses: actions/setup-java@v3.12.0
        with:
          java-version: 18
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.1

      - name: Compile
        run: ./gradlew clean build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          flags: unittest